apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-08-05T20:13:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: the-rights-machine
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":5454,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-08-05T20:13:34Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-08-05T20:14:16Z"
  name: the-rights-machine-service
  namespace: default
  resourceVersion: "5143"
  uid: daa13670-a12c-4504-82b7-6887ec1b69c7
spec:
  clusterIP: 10.30.70.102
  clusterIPs:
  - 10.30.70.102
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30624
    port: 5454
    protocol: TCP
    targetPort: 5454
  selector:
    app: the-rights-machine
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.105.169.101
