CREATE TABLE [dbo].[tRequest]
(
	[RequestID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Guid] UNIQUEIDENTIFIER NOT NULL, 
    [User] UNIQUEIDENTIFIER NOT NULL, 
    [Created] DATETIME NOT NULL DEFAULT (getdate())
)
