version: '3'
services:
  the-rights-machine:
    build: .
    restart: always
    ports:
      - "5454:5454"
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK