CREATE TABLE `tError` (
  `ErrorID` NVARCHAR(37) NOT NULL,
  `Code` INT NOT NULL,
  `Name` NVARCHAR(50) NOT NULL,
  `Description` NVARCHAR(200) NOT NULL,
  `Created` DATETIME NOT NULL
  PRIMARY KEY (`ErrorID`)
  );

