CREATE TABLE `tLine` (
  `LineID` NVARCHAR(37) NOT NULL,
  `ItemID` NVARCHAR(37) NOT NULL,
  `StartDate` DATETIME NOT NULL,
  `EndDate` DATETIME NOT NULL,
  `ExclusivityID` INT NOT NULL,
  `TypeID` INT NOT NULL,
  PRIMARY KEY (`LineID`)
  );

