CREATE TABLE `tMessage` (
  `MessageID` NVARCHAR(37) NOT NULL,
  `User` NVARCHAR(37) NOT NULL,
  `GUID` NVARCHAR(37) NOT NULL,
  `APIKey` NVARCHAR(37) NOT NULL,
  `Created` DATETIME NOT NULL,
  `Tag` NVARCHAR(37) NOT NULL,  
   PRIMARY KEY (`MessageID`)
);

