CREATE TABLE `tUser` (
  `UserID` NVARCHAR(37) NOT NULL,
  `Username` NVARCHAR(37) NOT NULL,
  `Email` NVARCHAR(1024) NOT NULL,
  `APIKey` NVARCHAR(37) NOT NULL,
  `GUID` NVARCHAR(37) NOT NULL,
  `Banned` BOOLEAN NOT NULL DEFAULT false,
  `Active` BOOLEAN NOT NULL DEFAULT false,
  `Verified` BOOLEAN NOT NULL DEFAULT false,
  `Created` DATETIME NOT NULL, 
  `Updated` DATETIME NULL, 
   PRIMARY KEY (`UserID`)
);

